ifneq ($(CONFIG_ARCH_QTI_VM), y)
dtbo-$(CONFIG_ARCH_PINEAPPLE) += display/pineapple-sde.dtbo
ifeq ($(CONFIG_TARGET_PRODUCT_HOUJI),y)
dtbo-y += display/houji-sde-display-mtp-overlay.dtbo
else ifeq ($(CONFIG_TARGET_PRODUCT_SHENNONG),y)
dtbo-y += display/shennong-sde-display-mtp-overlay.dtbo
else ifeq ($(CONFIG_TARGET_PRODUCT_SUIREN),y)
dtbo-y += display/suiren-sm8650-camera-sensor.dtbo
else ifeq ($(CONFIG_TARGET_PRODUCT_MANET),y)
dtbo-y += display/manet-sde-display-mtp-overlay.dtbo
else ifeq ($(CONFIG_TARGET_PRODUCT_AURORA),y)
dtbo-y += display/aurora-sde-display-mtp-overlay
else ifeq ($(CONFIG_TARGET_PRODUCT_GOKU),y)
dtbo-y += display/goku-sde-display-mtp-overlay.dtbo
else
dtbo-$(CONFIG_ARCH_PINEAPPLE) += \
		display/pineapple-sde-display-rumi-overlay.dtbo \
		display/pineapple-sde-display-cdp-overlay.dtbo \
		display/pineapple-sde-display-rcm-overlay.dtbo \
		display/pineapple-sde-display-mtp-overlay.dtbo \
		display/pineapple-sde-display-qrd-overlay.dtbo \
		display/pineapple-sde-display-hdk-overlay.dtbo \
		display/pineapple-sde-display-aim500-overlay.dtbo \
		display/pineapple-sde-display-cdp-nfc-overlay.dtbo \
		display/pineapple-sde-display-mtp-nfc-overlay.dtbo \
		display/pineapple-sde-display-atp-overlay.dtbo
endif
else
dtbo-$(CONFIG_ARCH_PINEAPPLE) += display/trustedvm-pineapple-sde-display-mtp-overlay.dtbo \
		  display/trustedvm-pineapple-sde-display-cdp-overlay.dtbo \
		  display/trustedvm-pineapple-sde-display-rumi-overlay.dtbo \
		  display/trustedvm-pineapple-sde-display-qrd-overlay.dtbo \
		  display/trustedvm-pineapple-sde-display-atp-overlay.dtbo
endif

ifneq ($(CONFIG_ARCH_QTI_VM), y)
dtbo-$(CONFIG_ARCH_KALAMA) += display/kalama-sde.dtbo \
		display/kalama-sde-display-rumi-overlay.dtbo \
		display/kalama-sde-display-cdp-overlay.dtbo \
		display/kalama-sde-display-cdp-wsa883x-overlay.dtbo \
		display/kalama-sde-display-mtp-overlay.dtbo \
		display/kalama-sde-display-qrd-overlay.dtbo \
		display/kalama-sde-display-hdk-overlay.dtbo \
		display/kalama-sde-display-hhg-overlay.dtbo \
		display/kalama-sde-display-mtp-nfc-overlay.dtbo \
		display/kalama-sde-display-rcm-overlay.dtbo \
		display/kalama-sde-display-cdp-nfc-overlay.dtbo \
		display/kalama-sde-display-atp-overlay.dtbo
else
dtbo-$(CONFIG_ARCH_KALAMA) += display/trustedvm-kalama-sde-display-mtp-overlay.dtbo \
                  display/trustedvm-kalama-sde-display-mtp-nfc-overlay.dtbo \
                  display/trustedvm-kalama-sde-display-cdp-nfc-overlay.dtbo \
		  display/trustedvm-kalama-sde-display-cdp-overlay.dtbo \
		  display/trustedvm-kalama-sde-display-cdp-wsa883x-overlay.dtbo \
		  display/trustedvm-kalama-sde-display-rumi-overlay.dtbo \
		  display/trustedvm-kalama-sde-display-qrd-overlay.dtbo \
		  display/trustedvm-kalama-sde-display-atp-overlay.dtbo
endif

ifneq ($(CONFIG_ARCH_QTI_VM), y)
dtbo-$(CONFIG_ARCH_CLIFFS) += display/cliffs-sde.dtbo \
		display/peridot-sde-display-mtp-overlay.dtbo \
		display/chenfeng-sde-display-mtp-overlay.dtbo \
		display/cliffs-sde-display-rumi-overlay.dtbo \
		display/cliffs-sde-display-cdp-overlay.dtbo \
		display/cliffs-sde-display-rcm-overlay.dtbo \
		display/cliffs-sde-display-mtp-overlay.dtbo \
		display/cliffs-sde-display-mtp-wcd9395-overlay.dtbo \
		display/cliffs-sde-display-qrd-overlay.dtbo \
		display/cliffs-sde-display-atp-overlay.dtbo
else
dtbo-$(CONFIG_ARCH_CLIFFS) += display/trustedvm-cliffs-sde-display-mtp-overlay.dtbo \
		  display/trustedvm-cliffs-sde-display-cdp-overlay.dtbo \
		  display/trustedvm-cliffs-sde-display-rumi-overlay.dtbo \
		  display/trustedvm-cliffs-sde-display-qrd-overlay.dtbo \
		  display/trustedvm-cliffs-sde-display-rcm-overlay.dtbo \
		  display/trustedvm-cliffs-sde-display-atp-overlay.dtbo
endif

ifneq ($(CONFIG_ARCH_QTI_VM), y)
dtbo-$(CONFIG_ARCH_PITTI) += display/pitti-sde.dtbo \
		display/pitti-sde-display-atp-overlay.dtbo \
		display/pitti-sde-display-idp-overlay.dtbo \
		display/pitti-sde-display-idp-amoled-overlay.dtbo \
		display/pitti-sde-display-idp-pmiv0104-overlay.dtbo \
		display/pitti-sde-display-qrd-overlay.dtbo \
		display/pitti-sde-display-rumi-overlay.dtbo
endif

ifeq ($(CONFIG_ARCH_SA8155), y)
dtbo-y += display/sa8155-adp-star-display.dtbo
endif

always-y    := $(dtb-y) $(dtbo-y)
subdir-y    := $(dts-dirs)
clean-files    := *.dtb *.dtbo
